// <auto-generated />
namespace BooksStore.Domain.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class _24_04_2020 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_24_04_2020));
        
        string IMigrationMetadata.Id
        {
            get { return "202004240512063_24_04_2020"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
